export const defaultRooms = [
  { room_name: "Auditorium", room_category: "Dewan / Ruang Umum", capacity: 300 },
  { room_name: "Bengkel Reka Bentuk", room_category: "Kesenian", capacity: 30 },
  { room_name: "Bilik Busana", room_category: "Kesenian", capacity: 25 },
  { room_name: "Bilik Mesyuarat", room_category: "Sokongan Sekolah", capacity: 20 },
  { room_name: "Bilik Peperiksaan", room_category: "Sokongan Sekolah", capacity: 40 },
  { room_name: "Bilik Smartboard Balada", room_category: "Smartboard / PdP", capacity: 35 },
  { room_name: "Bilik Smartboard Cindai", room_category: "Smartboard / PdP", capacity: 35 },
  { room_name: "Bilik Smartboard Inang", room_category: "Smartboard / PdP", capacity: 35 },
  { room_name: "Bilik Smartboard Muzikal", room_category: "Smartboard / PdP", capacity: 35 },
  { room_name: "Bilik Smartboard Seniman", room_category: "Smartboard / PdP", capacity: 35 },
  { room_name: "Bilik SPBT", room_category: "Sokongan Sekolah", capacity: 20 },
  { room_name: "Black Box", room_category: "Kesenian", capacity: 80 },
  { room_name: "Dewan Makan", room_category: "Dewan / Ruang Umum", capacity: 200 },
  { room_name: "Dewan Terbuka", room_category: "Dewan / Ruang Umum", capacity: 250 },
  { room_name: "Makmal Biologi", room_category: "Sains", capacity: 40 },
  { room_name: "Makmal Fizik", room_category: "Sains", capacity: 40 },
  { room_name: "Makmal Kimia", room_category: "Sains", capacity: 40 },
  { room_name: "Makmal Komputer 1", room_category: "ICT / Komputer", capacity: 35 },
  { room_name: "Makmal Komputer 2", room_category: "ICT / Komputer", capacity: 35 },
  { room_name: "Makmal Sains Integrasi 1", room_category: "Sains", capacity: 40 },
  { room_name: "Makmal Sains Integrasi 2", room_category: "Sains", capacity: 40 },
  { room_name: "Orkestra", room_category: "Kesenian", capacity: 50 },
  { room_name: "Studio Keyboard 1", room_category: "Kesenian", capacity: 20 },
  { room_name: "Studio Keyboard 2", room_category: "Kesenian", capacity: 20 },
  { room_name: "Studio Muzik Tradisional", room_category: "Kesenian", capacity: 30 },
  { room_name: "Studio Seni Halus", room_category: "Kesenian", capacity: 30 },
  { room_name: "Studio Tari 1", room_category: "Kesenian", capacity: 35 },
  { room_name: "Studio Tari 2", room_category: "Kesenian", capacity: 35 },
  { room_name: "Studio Teater 1", room_category: "Kesenian", capacity: 40 },
  { room_name: "Studio Viscom", room_category: "Kesenian", capacity: 30 },
  { room_name: "Studio Wayang Kulit", room_category: "Kesenian", capacity: 30 },
  { room_name: "Surau", room_category: "Dewan / Ruang Umum", capacity: 100 },
]
